Fix starlark-rust unused import issue
Summary:
Fix issue:
```
error: unused import: `pagable::PagableDeserialize`
  --> starlark-rust/starlark_syntax/src/codemap.rs:45:5
   |
45 | use pagable::PagableDeserialize;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: requested on the command line with `-D unused-imports`

error: unused import: `pagable::PagableSerialize`
  --> starlark-rust/starlark_syntax/src/codemap.rs:47:5
   |
47 | use pagable::PagableSerialize;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling buck2_query_derive v0.4.1 (/home/runner/work/buck2/buck2/app/buck2_query_derive)
error: unused import: `pagable::PagableDeserializer`
  --> starlark-rust/starlark_syntax/src/codemap.rs:46:5
   |
46 | use pagable::PagableDeserializer;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unused import: `pagable::PagableSerializer`
  --> starlark-rust/starlark_syntax/src/codemap.rs:48:5
   |
48 | use pagable::PagableSerializer;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Reviewed By: IanChilds

Differential Revision: D103431242

fbshipit-source-id: 5e23422a349f2f7deee61b4083c6a08643523d97